"""followers

Revision ID: 135bbee2ad04
Revises: e3bce2e4e3d3
Create Date: 2022-08-12 21:19:52.025645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135bbee2ad04'
down_revision = 'e3bce2e4e3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
